### PR TITLE
Switched to postion: sticky;

### PR DESCRIPTION
**Pull request by recursiveElk**
Current implementation with fixed doesn't work well with other content. Position sticky is used as a replacement with fallback to fixed. As shown at: https://codepen.io/recursiveElk/pen/xxOBGOK

Thanks for your implementation!

### CODE REVIEW

**Comment by moubi** [comment]
@recursiveElk thanks for your PR :)

Can you clarify on what is not working with `position: fixed;`? Is it that the sidebar is not visible (lack of styling) when scrolling over full width content?

A note on `position: sticky`: it isn't actually a full replacement of `fixed` since it makes the nav to behave differently. Fx. it stops being sticky when bumping into a full width content.

**Comment by recursiveElk** [comment]
Hey! Feel free to reject, just thought i'd send it your way because I adapted from your implementation and it helped me out.

Aware that position: sticky may not be intended effect but as shown in my codepen, if you switch it back to fixed you can see how the sidebar component interacts with the following (full-width) div. (overlapping)

I guess they could be considered two different use cases where in your case it's more around overarching navigation, where as for me I required something more modular :)

Either way, thanks for making this public and making my job a little easier 👍

**Comment by moubi** [comment]
Yes, the idea with the sticky nav is to always remain sticky.

But to cover your use case (or any other) a good solution would be to simply extend the `.scroll` class in your own app, adding the `position: sticky`. Or you can add another, specific to your app, class with custom rules.

That way we don't really need to deal with the `sticky-nav` lib.  It's actually a very old project 😄 Glad that it still helps.

**Comment by recursiveElk** [comment]
I will admit I actually found an old css only solution that I had made a while back during investigation 😂 Sometimes you have to solve something a few times before you remember. https://codepen.io/recursiveElk/pen/vYOOpzg.

Cheers, have a nice day!

**Pull request closed without merging**
